Extend codesign check

diff --git a/apple/sign_notarize_bundle b/apple/sign_notarize_bundle
--- a/apple/sign_notarize_bundle
+++ b/apple/sign_notarize_bundle
@@ -45,12 +45,36 @@ codesign -s "$APPLE_IDENTITY" --timestamp -o runtime "${BUNDLE}"
 
 echo '-------------------------------'
 echo 'Checking validity of the signed app bundle (without --deep):'
-codesign -d -vv "${BUNDLE}"
-codesign -d -vv "${BUNDLE}/Contents/MacOS/${MAIN_EXE}"
+
+# Run codesign with all indicated arguments $@.
+# Also check does the result contain lines Authority=...
+# that indicate this was properly signed.
+check_codesign()
+{
+  codesign "$@"
+  REQUIRED_AUTHORITY="Authority=${APPLE_IDENTITY}"
+  if ! codesign "$@" 2>&1 | grep --fixed-strings "$REQUIRED_AUTHORITY" > /dev/null; then
+    echo 'Codesigning validation error: Failed to find authority ${REQUIRED_AUTHORITY}, consult above output for details'
+    exit 1
+  fi
+  REQUIRED_AUTHORITY="Authority=Developer ID Certification Authority"
+  if ! codesign "$@" 2>&1 | grep --fixed-strings "$REQUIRED_AUTHORITY" > /dev/null; then
+    echo 'Codesigning validation error: Failed to find authority ${REQUIRED_AUTHORITY}, consult above output for details'
+    exit 1
+  fi
+  REQUIRED_AUTHORITY="Authority=Apple Root CA"
+  if ! codesign "$@" 2>&1 | grep --fixed-strings "$REQUIRED_AUTHORITY" > /dev/null; then
+    echo 'Codesigning validation error: Failed to find authority ${REQUIRED_AUTHORITY}, consult above output for details'
+    exit 1
+  fi
+}
+
+check_codesign -d -vv "${BUNDLE}"
+check_codesign -d -vv "${BUNDLE}/Contents/MacOS/${MAIN_EXE}"
 
 echo '-------------------------------'
 echo 'Checking validity of the signed app bundle (with --deep):'
-codesign -d -vv --deep "${BUNDLE}"
+check_codesign -d -vv --deep "${BUNDLE}"
 
 # Note that Apple notarization process is seriously FUBAR.
 # We need to create a temporay zip with app bundle (because "notarytool submit"
