Make "security find-identity..." check consistent

diff --git a/apple/sign_notarize_bundle b/apple/sign_notarize_bundle
--- a/apple/sign_notarize_bundle
+++ b/apple/sign_notarize_bundle
@@ -26,15 +26,15 @@ shift 2
 
 # error if excessive command-line parameters
 if [ $# -ne 0 ]; then
-  echo "ERROR: Excessive command-line parameters. Usage: $0 BUNDLE MAIN_EXE"
+  echo "Codesigning error: Excessive command-line parameters. Usage: $0 BUNDLE MAIN_EXE"
   exit 1
 fi
 
 echo '-------------------------------'
 echo 'Checking is our APPLE_IDENTITY valid (should be in the keychain):'
 security find-identity -p codesigning -v
-if ! grep --fixed-strings "$APPLE_IDENTITY" <(security find-identity -p codesigning -v); then
-  echo 'ERROR: APPLE_IDENTITY not found in the keychain!'
+if ! security find-identity -p codesigning -v | grep --fixed-strings "$APPLE_IDENTITY" > /dev/null; then
+  echo 'Codesigning error: APPLE_IDENTITY not found in the keychain!'
   exit 1
 fi
 
